### ISSUE TITLE
wrong concept of `validateResponse`

### ISSUE THREAD

**Issue by teemow** [giantswarm/client-go#4]
1. We should discuss if the utils method `validateResponse` is what we want. 
2. `validateResponse` should be called before asserting a response status.

Original Author: @zyndiecate
Created at 15-09-2014 10:05:11
Gitlab: [giantswarm/client-go!2](https://git.giantswarm.io/giantswarm/client-go/issues/2)

**Comment by zyndiecate** [comment]
Already done. Just closing.
